## Matrix Multiplication
** We will use tf.matmul() method
*Rules*


1.   Inner dimensions must match
     (m,n)@(n,p)
     for e.g.


*   (5,7)@(8,9) It will not work because n are different
*   (5,8)@(8,9) It will work because inner dimension is same


2.   The result matrix has the shape of outer dimension,
     means
     A (m,n)
     B (n,p)
     So result has (m,p)
     e.g (4,7)@(7,5)->(4,5)



In [2]:
import tensorflow as tf
import numpy as np

In [8]:
tensor_A = tf.constant([[1,2],[3,4],[4,5]], dtype=tf.int32)
tensor_B = tf.constant([[5,6],[7,8]], dtype=tf.int32)
print('Shape of A', tensor_A.shape)
print('Shape of B', tensor_B.shape)

Shape of A (3, 2)
Shape of B (2, 2)


In [10]:
tensor_C = tf.matmul(tensor_A, tensor_B)
print(tensor_C)
print('Shape of C', tensor_C.shape)

tf.Tensor(
[[19 22]
 [43 50]
 [55 64]], shape=(3, 2), dtype=int32)
Shape of C (3, 2)


In [12]:
X = tf.constant([
    [1.,0, -1.],
    [2.,3.,1.]
], dtype=tf.float32)
X

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  0., -1.],
       [ 2.,  3.,  1.]], dtype=float32)>

In [13]:
Y = tf.constant([
    [4.],
    [5.],
    [6.]
], dtype=tf.float32)
Y

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[4.],
       [5.],
       [6.]], dtype=float32)>

In [15]:
print('X-Shape', X.shape)
print('Y-Shape', Y.shape)

X-Shape (2, 3)
Y-Shape (3, 1)


In [14]:
Z = tf.matmul(X, Y)
print(Z)
print('Shape of Z', Z.shape)

tf.Tensor(
[[-2.]
 [29.]], shape=(2, 1), dtype=float32)
Shape of Z (2, 1)


In [19]:
print(f'X-Shape: {X.shape}, Y-Shape: {Y.shape}, Z-Shape: {Z.shape}')
print(X.numpy())
print(Y.numpy())
print(Z.numpy())

X-Shape: (2, 3), Y-Shape: (3, 1), Z-Shape: (2, 1)
[[ 1.  0. -1.]
 [ 2.  3.  1.]]
[[4.]
 [5.]
 [6.]]
[[-2.]
 [29.]]


## Transpose
Transpose swaps axes. For 2d matrix shape (m,n) become (n,m) after transpose

In [25]:
tensor_one = tf.constant([
    [[1,2],[2,3]],
    [[4,5],[6,7]]
], dtype=tf.int32)
print(tensor_one)
print('\nShape of tensor_one', tensor_one.shape)

tf.Tensor(
[[[1 2]
  [2 3]]

 [[4 5]
  [6 7]]], shape=(2, 2, 2), dtype=int32)

Shape of tensor_one (2, 2, 2)


In [26]:
tensor_one_transpose = tf.transpose(tensor_one)
print(tensor_one_transpose)
print('\nShape of tensor_one_transpose', tensor_one_transpose.shape)

tf.Tensor(
[[[1 4]
  [2 6]]

 [[2 5]
  [3 7]]], shape=(2, 2, 2), dtype=int32)

Shape of tensor_one_transpose (2, 2, 2)


In [28]:
# 3D Transpose with explcit axis permutation
tensor_two = tf.constant([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
], dtype=tf.int32)

print(tensor_two)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [29]:
t2_transpose = tf.transpose(tensor_two, perm=[0,2,1])
print(t2_transpose)

tf.Tensor(
[[[1 3]
  [2 4]]

 [[5 7]
  [6 8]]], shape=(2, 2, 2), dtype=int32)


## Reshape
- tf.reshape(tensor, new_shape)
- Change the shape whithout changing the data.
- *Rule*: The total number of elements must stay the same

In [32]:
tensor_three = tf.constant([
    [1,2,3],
    [4,5,6]
], dtype=tf.int32)
print(tensor_three)
print('Shape of tensor_three', tensor_three.shape)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape of tensor_three (2, 3)


In [33]:
tensor_three_reshape = tf.reshape(tensor_three, shape=(3,2))
print(tensor_three_reshape)
print('Shape of tensor_three_reshape', tensor_three_reshape.shape)
print('Number of elements are: ',tf.size(tensor_three_reshape).numpy())

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Shape of tensor_three_reshape (3, 2)
Number of elements are:  6


In [34]:
# Infer dimension
tensor_three_reshape_infer = tf.reshape(tensor_three, shape=(-1,2))
print(tensor_three_reshape_infer)
print('Shape of tensor_three_reshape_infer', tensor_three_reshape_infer.shape)
print('Number of elements are: ',tf.size(tensor_three_reshape_infer).numpy())

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Shape of tensor_three_reshape_infer (3, 2)
Number of elements are:  6


In [39]:
# Infer dimension
tensor_three_reshape_infer2 = tf.reshape(tensor_three, shape=(3,-1))
print(tensor_three_reshape_infer2)
print('Shape of tensor_three_reshape_infer2', tensor_three_reshape_infer2.shape)
print('Number of elements are: ',tf.size(tensor_three_reshape_infer2).numpy())

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Shape of tensor_three_reshape_infer2 (3, 2)
Number of elements are:  6


In [40]:
#TASK: Reshape (2,6) -> (3,4) and (1,12)
tensor_given = tf.constant([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12]
], dtype=tf.int32)
print(tensor_given)
print('Shape of tensor_given', tensor_given.shape)

tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]], shape=(2, 6), dtype=int32)
Shape of tensor_given (2, 6)


In [41]:
tensor_given_reshape = tf.reshape(tensor_given, shape=(3,4))
print(tensor_given_reshape)
print('Shape of tensor_given_reshape', tensor_given_reshape.shape)

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
Shape of tensor_given_reshape (3, 4)


In [42]:
tensor_given_reshape2 = tf.reshape(tensor_given, shape=(1,12))
print(tensor_given_reshape2)
print('Shape of tensor_given_reshape2', tensor_given_reshape2.shape)


tf.Tensor([[ 1  2  3  4  5  6  7  8  9 10 11 12]], shape=(1, 12), dtype=int32)
Shape of tensor_given_reshape2 (1, 12)
