In [18]:
#TensorFlow basic

In [19]:
import tensorflow as tf

In [20]:
print(tf.__version__)

2.19.0


In [21]:
#creatint tensor with constant
#function here that we can use to create
scalar=tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [22]:
scalar.ndim

0

In [23]:
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [24]:
vector.ndim

1

In [25]:
matrix=tf.constant([[5,9],[9,11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  9],
       [ 9, 11]], dtype=int32)>

In [26]:
matrix.ndim

2

In [27]:
second_matrix=tf.constant([[5,7],
                           [3,8],
                           [3,9],
                           [4,2],
                           [8,6]])

In [28]:
second_matrix

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[5, 7],
       [3, 8],
       [3, 9],
       [4, 2],
       [8, 6]], dtype=int32)>

In [29]:
second_matrix.ndim

2

In [30]:
third_matrix=tf.constant([[1,2,3],[2,4,6],[3,6,9],[4,8,12],[5,10,15],[6,12,18]])
third_matrix

<tf.Tensor: shape=(6, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]], dtype=int32)>

In [31]:
second_matrix=tf.constant([[5.6,7.4],[3.45,8.35],[3.11,99.23],[4.34,2.34],[8.4,6.32]],dtype=tf.float32)
print(second_matrix)

tf.Tensor(
[[ 5.6   7.4 ]
 [ 3.45  8.35]
 [ 3.11 99.23]
 [ 4.34  2.34]
 [ 8.4   6.32]], shape=(5, 2), dtype=float32)


In [32]:
scalar=tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [33]:
vector=tf.constant([10,20,30,40])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 20, 30, 40], dtype=int32)>

In [34]:
matrix=tf.constant([[10,20],[30,40]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [35]:
tensor=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [36]:
#find the shape,rank and size of tensors
print("Scalar Information")
print("Shape:",scalar.shape)
print("Dimension:",scalar.ndim)
print("Size:",tf.size(scalar))
print("Rank:",tf.rank(scalar).numpy())

Scalar Information
Shape: ()
Dimension: 0
Size: tf.Tensor(1, shape=(), dtype=int32)
Rank: 0


In [37]:
print("Vector Information")
print("Shape:",vector.shape)
print("Dimension:",vector.ndim)
print("Size:",tf.size(vector))
print("Rank:",tf.rank(vector).numpy())

Vector Information
Shape: (4,)
Dimension: 1
Size: tf.Tensor(4, shape=(), dtype=int32)
Rank: 1


In [38]:
print("Tensor Information")
print("Shape:",tensor.shape)
print("Dimension:",tensor.ndim)
print("Size:",tf.size(tensor))
print("Rank:",tf.rank(tensor).numpy())

Tensor Information
Shape: (2, 2, 2)
Dimension: 3
Size: tf.Tensor(8, shape=(), dtype=int32)
Rank: 3


In [39]:
#Creating tensor using variable
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [40]:
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [41]:
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [42]:
changeable_tensor[1].assign(75)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 75], dtype=int32)>

In [43]:
#unchangeable_tensor[0].assign(12)
#unchangeable_tensor
#will become error because you cannot change constant tensor. They are immutable(unchangeable)

In [44]:
#random tensors
random_tensor=tf.random.Generator.from_seed(42)
random_tensor=random_tensor.normal(shape=(3,2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [45]:
random_tensor_2=tf.random.uniform(shape=(300,150),minval=0,maxval=1)
random_tensor_2

<tf.Tensor: shape=(300, 150), dtype=float32, numpy=
array([[0.43613946, 0.26022148, 0.20895135, ..., 0.14034605, 0.20559108,
        0.9854753 ],
       [0.19071805, 0.78553355, 0.19739664, ..., 0.9249257 , 0.26958168,
        0.6208774 ],
       [0.13376272, 0.89544976, 0.29041052, ..., 0.09517395, 0.67856073,
        0.5205555 ],
       ...,
       [0.34333408, 0.68830097, 0.7845006 , ..., 0.21007705, 0.17978334,
        0.655072  ],
       [0.8427129 , 0.34425402, 0.5320623 , ..., 0.6371608 , 0.22207332,
        0.08933163],
       [0.9200382 , 0.22732103, 0.59401727, ..., 0.4203161 , 0.16864061,
        0.98681736]], dtype=float32)>

In [46]:
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.int16)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [47]:
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.float16)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=float16, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float16)>

In [48]:
#tensor for all
tensor_ones=tf.ones(shape=(3,4),dtype=tf.dtypes.float16)
tensor_ones

<tf.Tensor: shape=(3, 4), dtype=float16, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float16)>

In [49]:
import numpy as np
numpy_Array=np.arange(1,25,dtype=np.int16)
numpy_Array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [50]:
tensor_numpy=tf.constant(numpy_Array,shape=(2,3,4))
tensor_numpy

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [51]:
print("Tensor Information")
print("Shape:",tensor_numpy.shape)
print("Dimension:",tensor_numpy.ndim)
print("Rank:",tf.rank(tensor_numpy).numpy())
print("Size:",tf.size(tensor_numpy))
print("Data Type of elements:",tensor_numpy.dtype)
print("Element along axis 0:",tensor_numpy.shape[0])
print("Element along axis 1:",tensor_numpy.shape[1])
print("Element along axis 2:",tensor_numpy.shape[2])
print("Total number of element: \t",tf.size(tensor_numpy).numpy())

Tensor Information
Shape: (2, 3, 4)
Dimension: 3
Rank: 3
Size: tf.Tensor(24, shape=(), dtype=int32)
Data Type of elements: <dtype: 'int16'>
Element along axis 0: 2
Element along axis 1: 3
Element along axis 2: 4
Total number of element: 	 24


In [52]:
#working with items of each dimension
tensor_numpy[:3,:3,:3]

<tf.Tensor: shape=(2, 3, 3), dtype=int16, numpy=
array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]]], dtype=int16)>

In [53]:
#first element of each dimension
tensor_numpy[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int16, numpy=
array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]], dtype=int16)>

In [54]:
#Arithmethic operation with tensors add,sub,multi,div

In [55]:
tensor_1=tf.constant([[11,9],[2,5]])
tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  9],
       [ 2,  5]], dtype=int32)>

In [56]:
#tensor_1+15
tf.add(tensor_1,15)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 24],
       [17, 20]], dtype=int32)>

In [57]:
#tensor_1-5
tf.subtract(tensor_1,15)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ -4,  -6],
       [-13, -10]], dtype=int32)>

In [58]:
#tensor_1*2
tf.multiply(tensor_1,15)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[165, 135],
       [ 30,  75]], dtype=int32)>

In [59]:
#tensor_1/2
tf.divide(tensor_1,15)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.73333333, 0.6       ],
       [0.13333333, 0.33333333]])>

In [60]:
tensor_new=tf.square(tensor_1)
tensor_new

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  81],
       [  4,  25]], dtype=int32)>

In [62]:
second_matrix=tf.constant([
    [8,16],
    [64,8],
    [625,9.24],
    [125,2.34],
    [169,144]
  ],dtype=tf.float32)
print(second_matrix)

tf.Tensor(
[[  8.    16.  ]
 [ 64.     8.  ]
 [625.     9.24]
 [125.     2.34]
 [169.   144.  ]], shape=(5, 2), dtype=float32)


In [63]:
# Exercise
# Create two tensors with random values between 0 and 1 , shape is [6,300]
# **Find out the following details: **
# Number of elements
# Size,
# Rank,
# Shape

tensor_random_1 = tf.random.uniform(shape=(6, 300), minval=0, maxval=1)
tensor_random_2 = tf.random.uniform(shape=(6, 300), minval=0, maxval=1)

print("Tensor 1 Information")
print("Shape:", tensor_random_1.shape)
print("Dimension:", tensor_random_1.ndim)
print("Size:", tf.size(tensor_random_1).numpy())
print("Rank:", tf.rank(tensor_random_1).numpy())
print("Number of elements:", tf.size(tensor_random_1).numpy())

print("\nTensor 2 Information")
print("Shape:", tensor_random_2.shape)
print("Dimension:", tensor_random_2.ndim)
print("Size:", tf.size(tensor_random_2).numpy())
print("Rank:", tf.rank(tensor_random_2).numpy())
print("Number of elements:", tf.size(tensor_random_2).numpy())

Tensor 1 Information
Shape: (6, 300)
Dimension: 2
Size: 1800
Rank: 2
Number of elements: 1800

Tensor 2 Information
Shape: (6, 300)
Dimension: 2
Size: 1800
Rank: 2
Number of elements: 1800
